config/routes.rb
Rails.application.routes.draw do
  get 'contact', to: 'pages#contact', as: "contact"
  get 'projects', to: 'pages#projects', as: "projects"
  get 'about', to: 'pages#about', as: "about"
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def projects
  end

  def about
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="wrapper">
  <div class="container">
    <div class="banner-content">
      <div class="title">
        <h1>Shine Bright</h1>
      </div>
      <div class="subtitle">
        <h3>among the dim compitition. Ensure you have a website that shines.</h3>
      </div>
    </div>
  </div>
  <div class="intro-box">
    <p>Hello, my name is Brett. I bring to life scalable and reactive websites. If youd like to know more about me, check out the About section and see what I am up to in Projects. Enjoy! </p>
  </div>
  <div class="icons">
    <h3>Languages</h3>
    <ul>
      <li><p>Ruby</p>
        <%= image_tag("ruby.png", size: "50x50", :alt => "ruby") %></li>
      <li><p>Rails</p>
      <%= image_tag("rails-plain-wordmark.svg", size: "50x50", :alt => "rails") %></li>
      <li><p>HTML5</p>
        <%= image_tag("html5-original-wordmark.svg", size: "50x50", :alt => "html") %></li>
      <li><p>CSS3</p>
      <%= image_tag("css3-original-wordmark.svg", size: "50x50", :alt => "css") %></li>
      <li><p>Javascript</p>
      <%= image_tag("javascript-original.svg", size: "50x50", :alt => "javascript") %></li>
      <li><p>C#</p>
      <%= image_tag("csharp-original.svg", size: "50x50", :alt => "c sharp") %></li>
      <li><p>C++</p>
      <%= image_tag("cplusplus-original.svg", size: "50x50", :alt => "c plus plus") %></li>
      <li><p>Bootstrap</p>
        <%= image_tag("bootstrap-plain-wordmark.svg", size: "50x50", :alt => "bootstrap") %></li>
      <li><p>Heroku</p>
        <%= image_tag("heroku-original-wordmark.svg", size: "50x50", :alt => "heroku") %></li>
      <li><p>Yarn</p>
        <%= image_tag("yarn-original-wordmark.svg", size: "50x50", :alt => "yarn") %></li>
      <li><p>jQuery</p>
        <%= image_tag("jquery-plain-wordmark.svg", size: "50x50", :alt => "jqueery") %></li>
    </ul>
    <h3>Databases</h3>
    <ul>
      <li><p>MySQL</p>
      <%= image_tag("mysql-original-wordmark.svg", size: "50x50", :alt => "my sql") %></li>
      <li><p>PostgreSQL</p>
      <%= image_tag("postgresql-original-wordmark.svg", size: "50x50", :alt => "postgresql") %></li>
    </ul>
    <h3>Softwares</h3>
    <ul>
      <li><p>Ubuntu</p>
      <%= image_tag("ubuntu-plain-wordmark.svg", size: "50x50", :alt => "ubuntu") %></li>
      <li><p>Sublime Text</p>
      <%= image_tag("ruby.png", size: "50x50", :alt => "sublime text") %></li>
      <li><p>Microsoft Visual Studio</p>
      <%= image_tag("visualstudio-plain.svg", size: "50x50", :alt => "visual studo") %></li>
      <li><p>Netbeans</p>
      <%= image_tag("ruby.png", size: "50x50", :alt => "netbeans") %></li>
      <li><p>Live Code</p>
      <%= image_tag("ruby.png", size: "50x50", :alt => "live code") %></li>
      <li><p>Autodesk Maya</p>
      <%= image_tag("ruby.png", size: "50x50", :alt => "maya") %></li>
      <li><p>Autodesk 3DS Max</p>
      <%= image_tag("ruby.png", size: "50x50", :alt => "3DS max") %></li>
      <li><p>Adobe Creative Suite</p>
      <%= image_tag("ruby.png", size: "50x50", :alt => "adobe creative suite") %></li>
      <li><p>Unity</p>
      <%= image_tag("ruby.png", size: "50x50", :alt => "unity") %></li>
      <li><p>Unreal Engine 4</p>
      <%= image_tag("ruby.png", size: "50x50", :alt => "unreal engine 4") %></li>
    </ul>
    <h3>Currently Learning</h3>
    <ul>
      <li><p>Node.js</p></li>
      <%= image_tag("nodejs-original.svg", size: "50x50", :alt => "node.js") %></li>
      <li><p>Angular.js</p></li>
      <%= image_tag("angularjs-original.svg", size: "50x50", :alt => "angular.js") %></li>
      <li><p>MongoDB</p>
      <%= image_tag("mongodb-plain-wordmark.svg", size: "50x50", :alt => "mongodb") %></li>
      <li><p>React</p></li>
      <%= image_tag("react-original-wordmark.svg", size: "50x50", :alt => "react") %></li>
      <li><p>Typescript</p></li>
      <%= image_tag("typescript-original.svg", size: "50x50", :alt => "typescript") %></li>
      <li><p>Python</p></li>
      <%= image_tag("python-original-wordmark.svg", size: "50x50", :alt => "python") %></li>
    </ul>
  </div>
</div>
<div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

app/views/pages/projects.html.erb
<h1>Pages#projects</h1>
<p>Find me in app/views/pages/projects.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar">

  <!-- Navigation -->
  <div class="navbar-center hidden-xs hidden-sm">
  <span class="navbar-item navbar-link"><%= link_to "About", about_path %> </span>
  <span class="navbar-item navbar-link"><%= link_to "Projects", projects_path %> </span>
  <span class="navbar-item navbar-link"><%= link_to "Contact", contact_path %> </span>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>